SUMMARY = "Object-oriented filesystem paths"
DESCRIPTION = "pathlib offers a set of classes to handle filesystem paths. \
It offers the following advantages over using string objects: \
- No more cumbersome use of os and os.path functions. \
- Embodies the semantics of different path types. \
- Well-defined semantics, eliminating any warts or ambiguities. \
"
HOMEPAGE = "https://pypi.python.org/pypi/pathlib"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=3b6557c860f0fc867aeab30afd649753"
inherit pypi
