SUMMARY = "TinyDB is a tiny, document oriented database optimized for your happiness :)"
DESCRIPTION = "TinyDB is a lightweight document oriented database optimized for \
your happiness :) It’s written in pure Python and has no external dependencies. \
The target are small apps that would be blown away by a SQL-DB or an external \
database server. \
"
HOMEPAGE = "https://github.com/msiemens/tinydb"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=49903ea9c586b357ceb682e761818804"

inherit pypi
